spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todos?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
      format_sql: true

